redux
Ksaltotun/reactFunc pull request #1
Opened 2019-11-28 21:12 UTC by Ksaltotun

trainee with redux

2019-11-29 07:52 UTC, inthedark122 requested changes

2019-11-29 07:52 UTC, inthedark122 commented on public/index.html
> +<!DOCTYPE html>
в файле после генерации CRA написано больше, лучше оставлять как есть

2019-11-29 07:52 UTC, inthedark122 commented on src/app/guestsTable/guestsTable.js
> +  const peoplesList = peoples.map(pipl => {
map редко выносят в отдельную функцию, лучше все писать в общем return

2019-11-29 07:52 UTC, inthedark122 commented on src/app/guestsTable/guestsTable.js
> +  return <div className="jumbotron userList">{peoplesList}</div>;
```
return (
    <div className="jumbotron userList">
        {peoples.map(people => (
            <User key={people.id} id={people.id} name={people.name} age={people.age} />
        ))}
    </div>
);
```

2019-11-29 07:52 UTC, inthedark122 commented on src/app/inputForm/inputForm.js
> +import React from "react";
файлы с классами лучше называть либо в CamelCase `InputForm` либо с тере `input-form`
тоже касается и папок

2019-11-29 07:52 UTC, inthedark122 commented on src/app/inputForm/inputForm.js
> +    nameInput = event.target.value;
так не работает, надо сделать:
```
const [form, setForm] = useState({});

const handleChangeName = event => {
    setForm({...form, name: event.target.value});
}

const handleChangeAge = event => {
    setForm({...form, age: parseInt(event.target.value, 10)});
}

const handleSubmit = event => {
    // работу с event лучше вверху писать
    event.preventDefault();
    dispatch(addPeople(form.name, form.age));
    // лучше передавать объекты
    // dispatch(addPeople(form));
}

// Почему не использовать форму из react-bootstrap?
return (
    <form className="jumbotron inputForm" onSubmit={handleSubmit}>
        <span className="point">Enter your name</span>
        <input className="point" placeholder="name" onChange={handleChangeName} value={form.name} />
        <span className="point">Enter your age</span>
        <input className="point" placeholder="age" onChange={handleChangeAge} value={form.age}/>
        <button className="point" type="submit">Go!</button>
    </form>
);
```

2019-11-29 07:52 UTC, inthedark122 commented on src/reducers/reducer.js
> +const initpeoples = {
initialState

2019-12-02 06:03 UTC, Ksaltotun commented on public/index.html
> +<!DOCTYPE html>
там еще иконки, подключаются идругие штуки. Короче я поудалял все, предназначение чего не знал. Так что ок, больше не буду удалять.

2019-12-02 06:07 UTC, Ksaltotun commented on src/app/guestsTable/guestsTable.js
> +  const peoplesList = peoples.map(pipl => {
исправил

2019-12-02 06:07 UTC, Ksaltotun commented on src/app/guestsTable/guestsTable.js
> +  return <div className="jumbotron userList">{peoplesList}</div>;
исправил

2019-12-02 06:07 UTC, Ksaltotun commented on src/app/inputForm/inputForm.js
> +import React from "react";
сделал

2019-12-02 06:08 UTC, Ksaltotun commented on src/app/inputForm/inputForm.js
> +    nameInput = event.target.value;
переделал

2019-12-02 06:08 UTC, Ksaltotun commented on src/reducers/reducer.js
> +const initpeoples = {
переделал

2019-12-02 20:17 UTC, inthedark122 requested changes

2019-12-02 20:17 UTC, inthedark122 commented on src/app/App.js
> +sagaMiddleware.run(getPeoples);
сделать файл `stores/index.js` и поместить инициализацию сторы
```
const sagaMiddleware = createSagaMiddleware();
const store = createStore(reducer, applyMiddleware(sagaMiddleware));

sagaMiddleware.run(getPeoples);

2019-12-02 20:17 UTC, inthedark122 commented on src/app/App.js
> +const handlePushPeople = (name, age) => sagaMiddleware.run(pushPeople, name, age);
handlePushPeople  и handleDeletePeople  не должно так быть, должны быть перехватчики через takeLatest, takeEvery

2019-12-02 20:17 UTC, inthedark122 commented on src/app/GuestsTable/GuestsTable.js
> +  const {peoples, spiner} = useSelector(store => store);
лучше: `const {peoples, spiner} = useSelector({peoples, spiner}=> {peoples, spiner});`
но это не оптимизировано, лучше использовать несколько useSelector
`const spiner = useSelector({spiner}=> spiner);`
`const peoples = useSelector({peoples}=> peoples);`

2019-12-02 20:17 UTC, inthedark122 commented on src/app/GuestsTable/GuestsTable.js
> +  const {peoples, spiner} = useSelector(store => store);
в идеале использовать reselect или мемоизацию и отдавать объект, но это уже в дальнейшем надо будет разбираться

2019-12-02 20:17 UTC, inthedark122 commented on src/app/App.js
> +sagaMiddleware.run(getPeoples);
```
export function* peoplesSaga() {
  yield takeEvery("ADD_PEOPLE", addPeople)
}
```

2019-12-02 20:17 UTC, inthedark122 commented on src/saga/saga.js
> +}
почти верно, только экшены надо вызывать обычные, которые просто запустят пустой экшен с типом `PEOPLE_DELETE` а дальше уже с помощью takeEvery надо перехватить этот экшен и перенаправить на функцию deletePeople

2019-12-02 20:17 UTC, inthedark122 commented on src/saga/saga.js
> +}
при перехвате первый аргумент в deletePeople будет action, такой же как в reducer

2020-07-06 10:54 UTC, merged